spring.application.name=Bolao Copa Producao

spring.datasource.url=ec2-52-23-131-232.compute-1.amazonaws.com:5432/d1m09fuc05v675
spring.datasource.username=wjbjuofsauvlpk
spring.datasource.password=5fecdb5320a297388866f87b5ba545e0d227e4904bc0473805d37c1048638352

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.time-zone = America/Sao_Paulo