spring.application.name=Bolao Copa Producao

spring.datasource.url=babar.db.elephantsql.com:5432/qaglhqqi
spring.datasource.username=qaglhqqi
spring.datasource.password=9pMQx_iiIkjITpmgyckirhlSr80EB3NK

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.time-zone = America/Sao_Paulo