spring.application.name=Bolao Brasileiro Producao

spring.datasource.url=jdbc:postgresql://dpg-cim10dtgkuvinfkkjmfg-a.oregon-postgres.render.com:5432/bra2023_user
spring.datasource.username=bra2023_user
spring.datasource.password=84KQ0KvPqVqLEoVklE6UckNY4RcCtpS6

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jackson.time-zone = America/Sao_Paulo